security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            lazy: true
            provider: users_in_memory
            custom_authenticator: App\Security\AppAuthenticator
            logout:
                path: app_logout

            remember_me:
                secret: '%env(APP_SECRET)%'  # Utilise la clé secrète du fichier .env
                lifetime: 604800
                path: /

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_homepage

            entry_point: form_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/banned, roles: ROLE_BANNED }
